# Generated by Django 4.1.7 on 2023-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
