# Generated by Django 4.1.6 on 2023-03-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiontype',
            options={},
        ),
        migrations.RemoveField(
            model_name='admissiontype',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='admissiontype',
            name='updated_date',
        ),
    ]
