# Generated by Django 4.1.6 on 2023-04-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
    ]
