# Generated by Django 4.1.6 on 2023-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_remove_banner_description_remove_banner_link_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='department',
            name='video_url',
            field=models.TextField(null=True),
        ),
    ]
