# Generated by Django 4.1.6 on 2023-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_livestreamsnotification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feedback_comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='origin_comment_id',
            field=models.IntegerField(null=True),
        ),
    ]
