# Generated by Django 4.1.6 on 2023-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_comment_feedback_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='admissionsquestion',
            old_name='is_answer',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='admissionsquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
