# Generated by Django 4.1.6 on 2023-04-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsquestion',
            name='user_id',
        ),
    ]
