# Generated by Django 4.1.6 on 2023-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_remove_admissionsquestion_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsquestion',
            name='date_answer',
            field=models.DateTimeField(null=True),
        ),
    ]
