# Generated by Django 4.1.6 on 2023-05-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_alter_admissionsquestion_date_answer'),
        ('admissions', '0008_school'),
    ]

    operations = [
    ]
