# Generated by Django 4.2 on 2023-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_merge_20230505_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyquestions',
            name='question_content',
            field=models.TextField(),
        ),
    ]
